grafana.ini:
  server:
    domain: grafana.svc.jpruitt.dev
    root_url: "%(protocol)s://%(domain)s"
  auth.generic_oauth:
    enabled: true
    name: "Authentik"
    allow_sign_up: true
    scopes: "openid email profile groups"
    email_attribute_name: "email"
    auth_url: "https://auth.svc.jpruitt.dev/application/o/authorize/"
    token_url: "http://authentik-server.authentik.svc.cluster.local/application/o/token/"
    api_url: "http://authentik-server.authentik.svc.cluster.local/application/o/userinfo/"
    signout_redirect_url: "https://auth.svc.jpruitt.dev/application/o/grafana/end-session/"
    role_attribute_path: "contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
  database:
    type: postgres
    host: "postgresql.database.svc.cluster.local"
    name: "grafana"
    user: "grafana_user"
    ssl_mode: disable
persistence:
  type: pvc
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
ingress:
  enabled: true
  hosts:
    - "grafana.svc.jpruitt.dev"
  path: "/"
envValueFrom:

  GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
    secretKeyRef:
      name: grafana-postgres-secret
      key: auth-client-id
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
    secretKeyRef:
      name: grafana-postgres-secret
      key: auth-client-secret
  GF_DATABASE_PASSWORD:
    secretKeyRef:
      name: grafana-postgres-secret
      key: postgres-password

env:
  GF_SERVER_ROOT_URL: https://grafana.svc.jpruitt.dev

securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472
