name: Apps
on:
  push:
    paths:
      - 'apps/**'
      - '.github/workflows/apps.yml'

jobs:
  deploy:
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: hashicorp/setup-terraform@v4
      - run: cd apps && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock-timeout=300s

      - name: Cleanup state lock on failure or cancel
        if: cancelled() || failure()
        run: |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          curl -sk -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            https://kubernetes.default.svc/apis/coordination.k8s.io/v1/namespaces/terraform-states/leases/lock-tfstate-default-apps
