name: Apps
on:
  push:
    paths:
      - 'apps/**'
      - '.github/workflows/apps.yml'

jobs:
  deploy:
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: hashicorp/setup-terraform@v4
      - run: cd apps && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock-timeout=300s

      - name: Cleanup state lock on failure or cancel
        if: cancelled() || failure()
        run: kubectl delete lease lock-tfstate-default-apps -n terraform-states --ignore-not-found=true
