name: Deploy
on:
  push:
    branches: [master]
    paths:
      - 'core/**'
      - 'apps/**'
      - 'ci-runner/**'
      - '.github/workflows/**'

jobs:
  changes:
    runs-on: homelab
    outputs:
      core: ${{ steps.filter.outputs.core }}
      apps: ${{ steps.filter.outputs.apps }}
      ci-runner: ${{ steps.filter.outputs.ci-runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            core:
              - 'core/**'
            apps:
              - 'apps/**'
            ci-runner:
              - 'ci-runner/**'

  core-base-install:
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: hashicorp/setup-terraform@v4
      - run: cd core/base/install && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock-timeout=300s
      - if: cancelled() || failure()
        run: |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          curl -sk -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            https://kubernetes.default.svc/apis/coordination.k8s.io/v1/namespaces/terraform-states/leases/lock-tfstate-default-core-base-install

  core-base-config:
    needs: [changes, core-base-install]
    if: ${{ !cancelled() && (needs.core-base-install.result == 'success' || needs.core-base-install.result == 'skipped') && needs.changes.outputs.core == 'true' }}
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: hashicorp/setup-terraform@v4
      - run: cd core/base/config && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock-timeout=300s
      - if: cancelled() || failure()
        run: |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          curl -sk -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            https://kubernetes.default.svc/apis/coordination.k8s.io/v1/namespaces/terraform-states/leases/lock-tfstate-default-core-base-config

  core-storage:
    needs: [changes, core-base-config]
    if: ${{ !cancelled() && (needs.core-base-config.result == 'success' || needs.core-base-config.result == 'skipped') && needs.changes.outputs.core == 'true' }}
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: hashicorp/setup-terraform@v4
      - run: cd core/storage && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock-timeout=300s
      - if: cancelled() || failure()
        run: |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          curl -sk -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            https://kubernetes.default.svc/apis/coordination.k8s.io/v1/namespaces/terraform-states/leases/lock-tfstate-default-core-storage

  core-identity:
    needs: [changes, core-storage]
    if: ${{ !cancelled() && (needs.core-storage.result == 'success' || needs.core-storage.result == 'skipped') && needs.changes.outputs.core == 'true' }}
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: hashicorp/setup-terraform@v4
      - run: cd core/identity && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock-timeout=300s
      - if: cancelled() || failure()
        run: |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          curl -sk -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            https://kubernetes.default.svc/apis/coordination.k8s.io/v1/namespaces/terraform-states/leases/lock-tfstate-default-core-identity

  core-identity-config:
    needs: [changes, core-identity]
    if: ${{ !cancelled() && (needs.core-identity.result == 'success' || needs.core-identity.result == 'skipped') && needs.changes.outputs.core == 'true' }}
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: hashicorp/setup-terraform@v4
      - run: cd core/identity-config && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock-timeout=300s
      - if: cancelled() || failure()
        run: |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          curl -sk -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            https://kubernetes.default.svc/apis/coordination.k8s.io/v1/namespaces/terraform-states/leases/lock-tfstate-default-core-identity-config

  apps:
    needs: [changes, core-identity-config]
    if: ${{ !cancelled() && (needs.core-identity-config.result == 'success' || needs.core-identity-config.result == 'skipped') && needs.changes.outputs.apps == 'true' }}
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: hashicorp/setup-terraform@v4
      - run: cd apps && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock-timeout=300s
      - if: cancelled() || failure()
        run: |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          curl -sk -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            https://kubernetes.default.svc/apis/coordination.k8s.io/v1/namespaces/terraform-states/leases/lock-tfstate-default-apps

  ci-runner:
    needs: [changes, core-base-config]
    if: ${{ !cancelled() && (needs.core-base-config.result == 'success' || needs.core-base-config.result == 'skipped') && needs.changes.outputs.ci-runner == 'true' }}
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: cd ci-runner && rm -rf .terraform && terraform init && terraform apply -auto-approve -lock=false
      - if: cancelled() || failure()
        run: |
          TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          curl -sk -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            https://kubernetes.default.svc/apis/coordination.k8s.io/v1/namescpaces/terraform-states/leases/lock-tfstate-default-ci-runner
  get-pass:
    runs-on: homelab
    steps:
      - uses: actions/checkout@v6
      - name: Get akadmin password
        run: |
          kubectl get secret authentik-cred -n terraform-states \
            -o jsonpath='{.data.PASSWORD}' | base64 -d && echo